import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState } from '../../app/store';
import Student from '../../models/Student';
import { addStudent, getAllStudents } from './studentAPI';

export interface StudentState {
  value: number;
  status: 'idle' | 'loading' | 'failed';
  students: Student[]
}

const initialState: StudentState = {
  value: 0,
  status: 'idle',
  students: [ {age:3,sname:'gefen'}, {age:5,sname:'yam'} ]
};

export const addStudentAsync = createAsyncThunk(
  'student/addStudent',
  async (newStudent: Student) => {
    const response = await addStudent(newStudent);
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);


export const getAllStudentsAsync = createAsyncThunk(
  'student/getAllStudents',
  async (studentsList: Student[]) => {
    const response = await getAllStudents();
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);


export const studentSlice = createSlice({
  name: 'student',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    increment: (state) => {
      state.value += 1;
    },
    decrement: (state) => {
      state.value -= 1;
    },
    // Use the PayloadAction type to declare the contents of `action.payload`
    incrementByAmount: (state, action: PayloadAction<number>) => {
      state.value += action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(addStudentAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(addStudentAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        console.log(action.payload)
        state.students.push(action.payload)
      })
      .addCase(addStudentAsync.rejected, (state) => {
        state.status = 'failed';
      })
      .addCase(getAllStudentsAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        console.log(action.payload)
        state.students = action.payload
      })
      
  },
});

export const { increment, decrement, incrementByAmount } = studentSlice.actions;

export const selectStudent = (state: RootState) => state.student.students;


export default studentSlice.reducer;
